export const ANJALI_LIST_REQUEST = 'ANJALI_LIST_REQUEST';
export const ANJALI_LIST_SUCCESS = 'ANJALI_LIST_SUCCESS';
export const ANJALI_LIST_FAIL = 'ANJALI_LIST_FAIL';

export const ANJALI_CREATE_REQUEST = 'ANJALI_CREATE_REQUEST';
export const ANJALI_CREATE_SUCCESS = 'ANJALI_CREATE_SUCCESS';
export const ANJALI_CREATE_FAIL = 'ANJALI_CREATE_FAIL';

export const ANJALI_UPDATE_REQUEST = 'ANJALI_UPDATE_REQUEST';
export const ANJALI_UPDATE_SUCCESS = 'ANJALI_UPDATE_SUCCESS';
export const ANJALI_UPDATE_FAIL = 'ANJALI_UPDATE_FAIL';

export const ANJALI_DELETE_REQUEST = 'ANJALI_DELETE_REQUEST';
export const ANJALI_DELETE_SUCCESS = 'ANJALI_DELETE_SUCCESS';
export const ANJALI_DELETE_FAIL = 'ANJALI_DELETE_FAIL';
